name: dev

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  debugBuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akiojin/ue-build-github-action@v0.2.8
        with:
          version: UE_5.3
          configuration: DebugGame
